# # N = int(input())
# # N_list = set(int, input().split(' '))
# M = int(input())
# M_list = list(int, input().split(' '))
# print(type(M_list))
# # N_set = set(N_list)
# # M_set = set(M_list)
# # print(M_set & N_set)
# input()
# s1 = set(input().split())
# input()
# s2 = set(input().split())

input()
s1 = set(input().split())
input()
s2 = set(input().split())

print(s1&s2)